# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: No Time To Make It Shorter
author: Hildeberto Mendonça
description: In my personal website I write about myself, my career, my robbies and mainly about technology. My favorite topics are functional programming, software documentation, processes, and architecture. I use Python, Java and Clojure when talking about programming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hildeberto.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:year/:month/:title.html
excerpt_separator: "<!-- more -->"

twitter_username: htmfilho
github_username: htmfilho
google_analytics: UA-2938015-2
disqus:
  shortname: hildeberto

# Build settings
markdown: kramdown
kramdown:
  auto_ids: true

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude: [Gemfile,
          Gemfile.lock]

port: 4001
